### ISSUE TITLE
Revisit parameter and return types

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/module-mongodb#60]
**Description:**
$title.

For example, the `insert` method signature is currently the following:

```ballerina
public remote function insert(string collectionName, json? queryString) returns json | error {
   ...
}
```

Currently the `queryString` param is of type `json?` which is redundant since `()` is part of `json`. 

Anyway, insertion only works with JSON objects, and if anything else (e.g., number or array) is passed as the argument, it results in a **bad, sad error**. The parameter type has to be updated to reflect only the possible JSON values.

Even though the return type is `json|error`, nothing is returned, which I believe is being tracked for the error scenario with https://github.com/wso2-ballerina/module-mongodb/issues/56. However if the success scenario doesn't return a value or is `()`, the return type should ideally be `error?`.

**Comment by niveathika** [comment]
On hold now, since these changes will not be backward compatible
